name: Release Android

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the project to be released'
        required: true
        type: string
      path:
        description: 'Path of the project to be released'
        required: true
        type: string
      release-type:
        description: 'Release type of the project (debug/internal/production)'
        default: 'internal'
        type: string
      output-path:
        description: 'Path to get the APK file'
        required: true
        type: string
    secrets:
      project-id:
        description: 'WalletConnect Cloud ID'
        required: true
      firebase-app-id:
        required: true
      firebase-token:
        required: true
      relay-url:
        description: 'WalletConnect Relay URL'
        required: false
      sentry-dns:
        required: true
      sentry-file:
        required: true
      secrets-file:
        required: true
      keystore-name:
        required: true
      keystore:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/ci-setup

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: touch ${{ inputs.path }}/.env.${{ inputs.release-type }} && echo "ENV_PROJECT_ID=${{ secrets.project-id }}\nENV_RELAY_URL=${{ secrets.relay-url }}\nENV_SENTRY_DSN=${{ secrets.sentry-dns }}\nENV_SENTRY_TAG=${{ inputs.release-type }}" >> ${{ inputs.path }}/.env.${{ inputs.release-type }}
      - run: touch ${{ inputs.path }}/android/sentry.properties && echo "${{ secrets.sentry-file }}" >> ${{ inputs.path }}/android/sentry.properties
      - run: touch ${{ inputs.path }}/android/secrets.properties && echo "${{ secrets.secrets-file }}" >> ${{ inputs.path }}/android/secrets.properties
      - run: touch keystore.b64 && echo "${{ secrets.keystore }}" >> keystore.b64
      - run: base64 --decode -i keystore.b64 -o ${{ inputs.path }}/android/app/${{ secrets.keystore-name }}.keystore
      
      - name: Build APK
        run: cd ${{ inputs.path }} && yarn install && yarn run android:build:internal
  
      - name: Setup Firebase
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 13.0.1
          firebase_token: ${{ secrets.firebase-token }}
      
      - name: Upload APK
        env:
          APP_ID: ${{ secrets.firebase-app-id }}
        run: |
          firebase appdistribution:distribute ./android/app/build/outputs/apk/${{ inputs.output-path }} --app $APP_ID --release-notes "${{ inputs.name }} ${{ inputs.release-type }} release"
        